### ISSUE TITLE
Cannot shame those using Python <2.6

### ISSUE THREAD

**Issue by jonathansick** [adrn/shame#1]
The `format()` method and `print()` function are not available in earlier versions of Python.

**Comment by adrn** [comment]
damn 2.6 -- doesn't the `__future__` import solve the `print()` issue?

**Comment by jonathansick** [comment]
I mean to say Pythons earlier than 2.6. Python 2.6 and 2.7 can be rightfully shamed.

**Comment by adrn** [comment]
Oh! Yea, I mean, if someone is using Python < 2.6, they won't even get the joke

**Comment by jonathansick** [comment]
Somehow that does seem appropriate. I consider this issue resolved.

**Comment by adrn** [comment]
:)
